apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cpfkt123o-python 
  janus-idp.io/tekton: cpfkt123o-python
  backstage.io/kubernetes-id: cpfkt123o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cpfkt123o-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml